Vidya Kumari_22479
USE HR_DATA
(1)
SELECT * FROM OEHR_ORDERS
WHERE CAST(SUBSTRING(ORDER_DATE, 1, 9) AS DATE) = '2013-12-31'
(2)
SELECT * FROM OEHR_JOB_HISTORY
WHERE YEAR(START_DATE) >= 2010 AND YEAR(END_DATE) <= 2015;
(3)
SELECT ORDER_MODE, ORDER_STATUS,
COUNT(ORDER_ID)
FROM OEHR_ORDERS
GROUP BY ORDER_MODE, ORDER_STATUS;
(4)
SELECT DEPARTMENT_ID,
COUNT(EMPLOYEE_ID) AS 'HEAD_COUNT', AVG(SALARY) AS 'AVG_SALARY', SUM(SALARY) AS 'TOTAL_SALARY'
FROM OEHR_EMPLOYEES
GROUP BY DEPARTMENT_ID;
(5)
SELECT COUNTRY_ID,
COUNT(CUSTOMER_ID) AS 'TOTAL_CUSTOMERS', COUNT(DISTINCT CUSTOMER_ID) AS 'UNIQUE_CUSTOMERS'
FROM OEHR_CUSTOMERS
GROUP BY COUNTRY_ID;
(6)
SELECT CITY, 
COUNT(CUSTOMER_ID) AS 'NO_OF_CUSTOMERS'
FROM OEHR_CUSTOMERS
WHERE CITY LIKE 'S%'
GROUP BY CITY;
(7)
SELECT 
COUNT(CUSTOMER_ID)
FROM OEHR_CUSTOMERS
WHERE CUST_EMAIL NOT LIKE '%GMAIL%'
(8)
SELECT SALES_REP_ID,
COUNT(ORDER_ID) AS 'TOTAL_ORDERS'
FROM OEHR_ORDERS
GROUP BY SALES_REP_ID
(9)
SELECT YEAR(CAST(SUBSTRING (ORDER_DATE,1,9) AS DATE)) AS ORD_YEAR, COUNT(*) AS TOT_ORDERS
FROM OEHR_ORDERS 
GROUP BY YEAR(CAST(SUBSTRING (ORDER_DATE, 1,9) AS DATE));
(10)
SELECT DISTINCT POSTAL_CODE
FROM OEHR_CUSTOMERS




