VIDYA KUMARI 22479
USE HR_DATA
1)
SELECT E.FIRST_NAME, E.LAST_NAME, E.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM OEHR_EMPLOYEES E
INNER JOIN OEHR_DEPARTMENTS D 
          ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
2)
SELECT E.FIRST_NAME , E.LAST_NAME , 
       E.DEPARTMENT_ID ,  D.DEPARTMENT_NAME 
         FROM OEHR_EMPLOYEES E 
         INNER JOIN OEHR_DEPARTMENTS D 
          ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
          WHERE E.DEPARTMENT_ID = 80 OR E.DEPARTMENT_ID = 40
           ORDER BY E.LAST_NAME
3)
SELECT E.FIRST_NAME , E.LAST_NAME , 
       E.DEPARTMENT_ID ,  D.DEPARTMENT_NAME 
         FROM OEHR_EMPLOYEES E 
         INNER JOIN OEHR_DEPARTMENTS D 
          ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
          WHERE FIRST_NAME LIKE '%Z%'
4)
SELECT E.FIRST_NAME , E.LAST_NAME , 
       E.DEPARTMENT_ID ,  D.DEPARTMENT_NAME 
         FROM OEHR_EMPLOYEES E 
         FULL OUTER JOIN OEHR_DEPARTMENTS D 
          ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
5)
SELECT D.DEPARTMENT_NAME , L.CITY , 
       L.STATE_PROVINCE 
         FROM OEHR_DEPARTMENTS D 
         FULL OUTER JOIN OEHR_LOCATIONS L 
          ON D.LOCATION_ID = L.LOCATION_ID
6)
SELECT E.FIRST_NAME , E.LAST_NAME , 
       E.DEPARTMENT_ID ,  D.DEPARTMENT_NAME 
         FROM OEHR_EMPLOYEES E 
         LEFT OUTER JOIN OEHR_DEPARTMENTS D 
          ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
7)
SELECT AVG(SALARY) AS AVG_SALARY, COUNT(EMPLOYEE_ID) AS TOTAL_EMPLOYEES, 
OEHR_DEPARTMENTS.DEPARTMENT_NAME
FROM OEHR_EMPLOYEES
INNER JOIN OEHR_DEPARTMENTS
ON OEHR_EMPLOYEES.DEPARTMENT_ID = OEHR_DEPARTMENTS.DEPARTMENT_ID
GROUP BY DBO.OEHR_DEPARTMENTS.DEPARTMENT_NAME

8)
SELECT FIRST_NAME, LAST_NAME, DEPARTMENT_NAME
FROM OEHR_EMPLOYEES
INNER JOIN OEHR_DEPARTMENTS
ON OEHR_EMPLOYEES.MANAGER_ID = OEHR_DEPARTMENTS.MANAGER_ID

9)
SELECT  COUNT(E.EMPLOYEE_ID) AS TOTAL_EMPLOYEES, 
       E.DEPARTMENT_ID ,  D.DEPARTMENT_NAME 
         FROM OEHR_EMPLOYEES E 
         INNER JOIN OEHR_DEPARTMENTS D 
          ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
          WHERE SALARY > 10000
		  GROUP BY E.DEPARTMENT_ID, D.DEPARTMENT_NAME


