--VIDYA KUMARI
USE HR_DATA
--q10 Find the employee with the 3rd highest salary.
SELECT TOP 1 FIRST_NAME, MAX(Salary) AS MaxSalary 
FROM dbo.OEHR_EMPLOYEES
WHERE SALARY NOT IN (SELECT TOP 2 SALARY FROM dbo.OEHR_EMPLOYEES ORDER BY SALARY DESC)
GROUP BY FIRST_NAME
ORDER BY 2 DESC;



